accounts/urls.py
#django
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "accounts"
urlpatterns = [
    #extension: /accounts/
    path("", views.LoginFormView.as_view(redirect_authenticated_user=True), name ="index"),
    path("dashboard/", login_required(views.DashboardView.as_view()), name ="dashboard"),
    path("logout/", views.LogoutFormView.as_view(), name="logout"),
    path("list_account/", login_required(views.ActiveAccountFunc),name="list_account"),
    path("list_account/create/", login_required(views.CreateAccounts), name="create_account"),
    path("list_account/edit/<int:pk>/", login_required(views.EditAccountView.as_view()), name="edit"),
    path("list_account/edit/layoff_layon/<str:account_name_id>/<str:email>/<int:status>", login_required(views.LayoffLayonAccountFunc), name="layoff_layon"),
    path("list_account/detail/<int:pk>/", login_required(views.DetailAccountFunc), name="detail"),
    path("sales/", login_required(views.SaleFunc),name="sales"),
    path("sales/redeem/find", login_required(views.FindCuponFunc),name="find_cupon"),
    path("sales/redeem/<int:pk>", login_required(views.RedeemFunc),name="redeem"),
    path("sales/renew/<int:pk>/", login_required(views.RenewSale), name="renew_sale"),
    path("sales/update/<int:pk>/", login_required(views.UpdateSale), name="update_sale"),
    path("sales/update/change_sale/<int:pk>/", login_required(views.ChangeSaleFunc), name="change_sale"),
    path("sales/create/<int:pk>", login_required(views.NewSaleFunc), name='create'),
    path("customer/create/", login_required(views.NewCustomerFunc), name='new_customer'),
    path("release/<int:pk>/<int:user>/", login_required(views.ReleaseAccountFunc), name='release')
    ]

cuentas_mexico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'))
]

accounts/views.py
#python
import datetime
from uuid import UUID
from dateutil.relativedelta import relativedelta


#django
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import permission_required
from django.contrib import messages
from django.utils import timezone


#local
from .models import Account,AccountName,UserDetail,Status,Sale,Customer,PaymentMethod, Bank, Cupon
from .forms import CreateAccountForm, FilterAccountForm, EditAccountForm, SaleForm, UpdateSaleForm, ChangeSaleForm, NewCustomerForm, RedeemForm, FindCuponForm
from .functions import SearchExistent, UpdateAccount


## Login - Logour
class LoginFormView(LoginView):
    """
    Show Login page
    """
    template_name= 'accounts/index.html'
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Iniciar Sesión'
        return context

class LogoutFormView(LogoutView):
    """
    Logout user
    """
    pass

# Admin Views
class DashboardView(generic.TemplateView):
    """
    Show all data of template
    """
    model = User
    template_name = 'accounts/dashboard.html'
    today_sales=514
    year_sales=today_sales*365
    comparation = 3.5
    goal = 75

    def get_color(goal):
        if goal <= 30:
            return 'danger'
        elif goal >=31 and goal <= 70:
            return 'warning'
        else:
            return 'success'

    def get_best_sellers(day=None,year=None):
        best_seller = {
            'Netflix':{
            'value':500,
            'percentage':25
            },
            'Spotify':{
            'value':2000,
            'percentage': 75
            }
        }
        return best_seller

    def chart_data(object_data):
        """
        Get an object (dict), and return a list with labels
        """
        labels=[]
        datas=[]
        for label,data in object_data.items():
            labels.append(label)
            datas.append(list(data.values())[0])
        return labels,datas

    def get_context_data(self, **kwargs):
        goal = self.goal
        context = super().get_context_data(**kwargs)
        context['today_sale'] = self.today_sales
        context['year_sale'] = self.year_sales
        context['comparation'] = self.comparation
        context['goal'] = goal
        context['color'] = DashboardView.get_color(goal)
        context['best_sellers_day'] = DashboardView.get_best_sellers(day=timezone.now())
        context['best_sellers_day_label'] = DashboardView.chart_data(context['best_sellers_day'])[0]
        context['best_sellers_day_data'] = DashboardView.chart_data(context['best_sellers_day'])[1]
        context['best_sellers_year'] = DashboardView.get_best_sellers(year=datetime.datetime.today().strftime('%Y'))
        return context

@permission_required('accounts.view_account', raise_exception=True)
def ActiveAccountFunc(request):
    """
    Show all active accounts filtered by Bussiness ID of person are looking for And Pagintate by 10
    """
    business_id = SearchExistent.get_business_id(request)
    available_accounts = SearchExistent.get_available_accounts(request)
    form = FilterAccountForm()
    if request.method == 'POST':
        account_name_id=request.POST['account_name_id']
        email = request.POST['email']
        status_id = request.POST['status_id']
        if email == '---------':
            accounts = Account.objects.filter(
            business_id= business_id,
            account_name_id=account_name_id,
            status_id=status_id
            )
        else:
            accounts = Account.objects.filter(
                business_id= business_id,
                account_name_id=account_name_id,
                email=email,
                status_id=status_id
                )
            #Set Up Pagination
        p =Paginator(accounts, 9)
        page = request.GET.get('page')
        venues = p.get_page(page)
        return render(request, "accounts/active_accounts.html",{
            "accounts": accounts,
            "venues": venues,
            "form": form,
            'available_accounts':available_accounts
        })
    else:
        active = 1
        accounts = Account.objects.filter(status_id=active, business_id= business_id)
            #Set Up Pagination
        p =Paginator(accounts, 9)
        page = request.GET.get('page')
        venues = p.get_page(page)
        return render(request, "accounts/active_accounts.html",{
            "accounts": accounts,
            "venues": venues,
            "form": form,
            'available_accounts':available_accounts
        })

def CreateAccounts(request):
    """
    Add new account to actual bussines are loged in
    """
    if request.method == 'POST':
        form = CreateAccountForm(request.POST)
        user_details = UserDetail
        account = request.POST['account_name_id']
        perfil = AccountName.objects.get(pk=account)
        perfil = perfil.perfil_quantity
        
        if form.is_valid():
            for new_profile in range(1,perfil+1):
                account_name_id = form.cleaned_data['account_name_id']
                supplier = form.cleaned_data['supplier']
                expiration_date = form.cleaned_data['expiration_date']
                email = form.cleaned_data['email']
                password = form.cleaned_data['password']
                pin = form.cleaned_data['pin']
                comments = form.cleaned_data['comments']
                business = form.cleaned_data['business']
                created_by = form.cleaned_data['created_by']
                modified_by = form.cleaned_data['modified_by']
                exist = SearchExistent.search_by_email_account_id(
                    models=Account,
                    account_id=account_name_id,
                    email=email,
                    profile=new_profile
                    )
                if exist == False:
                    Account.objects.create(
                        account_name_id=account_name_id,
                        supplier=supplier,
                        expiration_date=expiration_date,
                        email=email,
                        password=password,
                        pin=pin,
                        comments=comments,
                        business=business,
                        created_by=created_by,
                        modified_by=modified_by,
                        profile=new_profile
                        )
                else:
                    return render(request, 'accounts/create_account.html',{
                        'form': form,
                        'error_message': f"El {account_name_id} con E-Mail {email} ya fue utilizado. Porfavor intenta con uno nuevo."
                    })
        else:
            raise Exception("Formulario No Valido")
        return redirect('accounts:list_account')
    else: 
        form = CreateAccountForm()
    return render(request, 'accounts/create_account.html', {
        'form': form,
    }
        )

class EditAccountView(UpdateView):
    model = Account
    form_class = EditAccountForm
    template_name = 'accounts/update_accounts.html'
    success_url = reverse_lazy('accounts:list_account')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

def DetailAccountFunc(request, pk):
    
    detail = Sale.objects.filter(account_id = pk)

    return render(request,'accounts/detail.html', {
        'detail':detail
    })

def SaleFunc(request,customer=None):
    if request.method=='POST':
        try:
            if customer == None:
                customer = request.POST["customer"]
            else:
                customer = customer

            is_email = False
            is_phone = False
            # now = datetime.now()
            #check if data is email or phone number
            if customer.isnumeric():
                is_phone = True
            else:
                is_email = True
        
                #get customer_id
            if is_email == True:
                customer_id = Customer.objects.get(email__contains=customer)
            if is_phone == True:
                customer_id = Customer.objects.get(phone__contains=customer)
            

            sale_page = SearchExistent.get_customer_sales(request,customer_id=customer_id)
            return render(request,'accounts/sales.html',sale_page)
                
        except(Http404):
            return render(request, "accounts/sales.html",{
                "error_message": "El cliente no existe, verifica que no tenga el codigo de pais"
            })
    return render(request,'accounts/sales.html',{
        'available_accounts':SearchExistent.get_available_accounts(request),
        'new_client': True
    })

def RenewSale(request,pk):
    sale = Sale.objects.get(pk=pk)
    form = SaleForm(request.POST or None, instance=sale)
    available_accounts = SearchExistent.get_available_accounts(request)

    if request.method == 'POST':
        if form.is_valid():
            #find all values
            new_expiration = int(form.data['new_expiration'])
            business = form.cleaned_data['business']
            user_seller_id = form.cleaned_data['user_seller_id']
            bank_id = form.cleaned_data['bank_id']
            customer_id = form.cleaned_data['customer_id']
            account_id = form.cleaned_data['account_id']
            status_id = form.cleaned_data['status_id']
            payment_method_id = form.cleaned_data['payment_method_id']

accounts/templates/accounts/change_sale.html
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Cambiar Cuenta</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <form action="{% url 'accounts:change_sale' current_sale.id %}" method="POST">
            {% csrf_token %}

            <div class="modal-body mb-3">
                <div class="mb-3">
                    <h2>Selecciona una Cuenta</h2>
                    <br>
                    <p>
                        <strong>Cuenta Actual: </strong> {{current_sale.account_id.email}}
                        <strong>Perfil: </strong> {{current_sale.account_id.profile}}
                    </p>
                    <p><strong>Vencimiento del cliente: </strong> {{current_sale.expiration_date|date:'d-M-Y'}}</p>

                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">E-mail</th>
                                <th scope="col">Perfil</th>
                                <th scope="col">Vencimiento Cuenta</th>
                                <th scope="col">#</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for disponible in avaiable_to_change %}
                            <!--show only active accounts-->
                            <tr>
                                <th scope="row">
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="{{form.account_id.name}}"
                                            id="{{disponible.id}}" value="{{disponible.id}}" required>
                                        <label class="form-check-label"
                                            for="{{disponible.id}}">{{disponible.email}}</label>
                                    </div>
                                </th>
                                <td>{{disponible.profile}}</td>
                                <td>{{disponible.expiration_date|date:"d-M-Y"}}</td>
                                <td>
                                    <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas"
                                        data-bs-target="#a{{disponible.id}}" aria-controls="offcanvasExample">
                                        Detalles
                                    </button>
                                </td>
                            </tr>

                            <!-- SHOW ACCOUNTS DETAILS-->
                            <div class="offcanvas offcanvas-start" tabindex="-1" id="a{{disponible.id}}"
                                aria-labelledby="offcanvasExampleLabel">
                                <div class="offcanvas-header">
                                    <h3 class="offcanvas-title" id="offcanvasExampleLabel">Detalles</h3>
                                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas"
                                        aria-label="Close"></button>
                                </div>
                                <div class="offcanvas-body">
                                    <div>
                                        <strong>
                                            <h4>{{disponible.account_name_id}} {{disponible.email}}</h4>
                                        </strong>
                                        <br>
                                        {% for details in all_account %}
                                        {% if details.email == disponible.email and details.account_name_id == disponible.account_name_id %}
                                        <h5>Perfil: {{details.profile}}</h5>
                                        <p><strong>Vencimiento Cuenta: </strong>{{details.expiration_date|date:'d-M-Y'}}
                                        </p>
                                        <p><strong>Vencimiento Cliente:</strong>
                                            {% for expiration_sale in sales %}
                                            {% if details.id == expiration_sale.account_id.id  %}
                                            {{expiration_sale.expiration_date|date:'d-M-Y' }}

                                            {% endif %}
                                            {% endfor %}
                                        </p>
                                        <br>
                                        {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <!-- END SHOW DETAILS-->
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </form>
    </div>
</div>

accounts/templates/accounts/create_account.html
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Crear Nueva Cuenta</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{% url 'accounts:create_account' %}" method="post">
            {% csrf_token %}
            <div class="modal-body">

                {% if error_message %}
                <p><strong>{{error_message}}</strong></p>
                {% endif %}
                <div class="mb-3">
                    <label for="account_name_id" class="form-label">{{form.account_name_id.label}}</label>
                    {{form.account_name_id}}
                </div>
                <div class="mb-3">
                    <label for="expiration_date" class="form-label">{{form.expiration_date.label}}</label>
                    {{form.expiration_date}}
                </div>

                <div class="mb-3">
                    <label for="email" class="form-label">{{form.email.label}}</label>
                    {{form.email}}
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">{{form.password.label}}</label>
                    {{form.password}}
                </div>
                <div class="mb-3">
                    <label for="pin" class="form-label">{{form.pin.label}}</label>
                    {{form.pin}}
                </div>
                <div class="mb-3">
                    <label for="renovable" class="form-label">{{form.renovable.label}}</label>
                    {{form.renovable}}
                </div>

                <div class="mb-3">
                    <label for="supplier" class="form-label">{{form.supplier.label}}</label>
                    {{form.supplier}}
                </div>
                <div class="mb-3">
                    <label for="comments" class="form-label">{{form.comments.label}}</label>
                    {{form.comments}}
                </div>
    
                    <input type="hidden" value="{{user.userdetail.business_id}}" name="business">
                    <input type="hidden" value="{{user.id}}" name="created_by">
                    <input type="hidden" value="{{user.id}}" name="modified_by">
                    <input type="hidden" value="1" name="profile">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <input type="submit" class="btn btn-primary" value="Crear">
            </div>
        </form>
    </div>
</div>

accounts/templates/accounts/detail.html
{% extends 'template.html' %}
{% block body %}
{% if not detail%}
<p>No hay datos disponibles</p>
<a href="{% url 'accounts:list_account' %}">volver</a>
{% endif %}
{% for details in detail %}
{% if user.userdetail.business == details.business %}

<p>{{details.created_at}}</p>
<p>{{details.expiration_date}}</p>
<p>{{details.payment_amount}}</p>
<p>{{details.invoice}}</p>
<p>{{details.bank_id}}</p>
<p>{{details.business}}</p>
{% else %}
<h1>Error 403</h1>
<p><strong>No puedes acceder a esta página</strong></p>
{% endif%}
{% endfor %}
{% endblock body %}

accounts/templates/accounts/find_cupon.html
<div class="modal-dialog modal-dialog-centered" role="document" >
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Buscar Cupón</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action="{% url 'accounts:find_cupon' %}" method="POST">
        {% csrf_token %}
      <div class="modal-body">
        {{form.as_p}}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-primary">Buscar</button>
      </div>
      <form>
    </div>
  </div>

accounts/templates/accounts/sales.html
<!--TEMPLATE-->
{% extends 'template.html' %}
{% block body %}

<!--AVAILABLE ACCOUNTS-->
{% if available_accounts %}
<h5> Cuentas Disponibles:</h5>
<p>
{% for available in available_accounts %}
{{available}}
{% endfor %}
</P>
{% endif %}

<!--CREATE NEW CUSTOMER-->
{% if new_client %}
<H1>Ventas</H1>
<br>
<button type="button" onclick="abrir_modal_edicion('{% url 'accounts:new_customer' %}')" class="btn btn-success">Crear Nuevo Cliente</button>
{% endif %}

<!--CUSTOMER ORDERS DETAIL-->
{% if not new_client %}

<h1>Detalles de {{customer.name}}</h1>

<div class="buttons">
    <button type="button" onclick="abrir_modal_edicion('{% url 'accounts:create' customer.id %}')"
        class="btn btn-success">Nueva Venta</button>
    <button type="button" onclick="abrir_modal_edicion('{% url 'accounts:redeem' customer.id %}')" class="btn btn-primary">Canjear Cupón</button>
    <button type="button" class="btn btn-secondary">Secondary</button>
    <button type="button" class="btn btn-danger">Danger</button>
    <button type="button" class="btn btn-warning">Warning</button>
    <button type="button" class="btn btn-info">Info</button>
    <button type="button" class="btn btn-light">Light</button>
    <button type="button" class="btn btn-dark">Dark</button>

    <button type="button" class="btn btn-link">Link</button>
</div>
<section class="activas">
    <div class="header">
        <h4 class="modal-title">Cuentas Activas</h4>
    </div>
    <div class="body">
        {% if not active_sales %}
        <div class="not_found">
            <h4>No hay cuentas activas</h4>
        </div>
        {% endif %}

        {% for detail in active_sales %}

        <div class="detail">
            <div class="account">
                <span>Cuenta:</span>
                <p>{{detail.account_id.account_name_id}}</p>
            </div>
            <div class="username">
                <span>Username:</span>
                <p>{{detail.account_id.email}}
                    {% if detail.account_id.renovable == True %}
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-star-fill gold" viewBox="0 0 16 16">
                        <path
                            d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                    </svg>
                    {% endif %}
                </p>
            </div>
            <div class="password">
                <span>Password:</span>
                <p>{{detail.account_id.password}}</p>
            </div>
            <div class="perfil">
                <span>Perfil:</span>
                <p>{{detail.account_id.profile}}</p>
            </div>
            <div class="pin">
                <span>Pin:</span>
                <p>{{detail.account_id.pin}}</p>
            </div>
            <div class="expiration_customer">
                <span>Vencimiento Cliente:</span>
                <p>{{detail.expiration_date|date:'d-M-Y' }}</p>
            </div>
            <div class="expiration_account">
                <span>Vencimiento Cuenta:</span>
                <p>{{detail.account_id.expiration_date|date:'d-M-Y'}}</p>
            </div>
            <div class="user_seller_id">
                <span>Modificado por:</span>
                <p>{{detail.user_seller_id}}</p>
            </div>

        </div>

        <div class="footer">
            <textarea class="copy" id="textArea"> http://cuentasmexico.mx/customers/{{customer.id}}/ </textarea>
            <button onclick="copyToClipBoard()" class="btn btn-primary">Copiar</button>
            <button onclick="abrir_modal_edicion('{% url 'accounts:renew_sale' detail.id %}')"
                class="btn btn-success">Renovar</button>
            <button onclick="abrir_modal_edicion('{% url 'accounts:update_sale' detail.id %}')" class="btn btn-warning">Editar</button>
            <button onclick="abrir_modal_edicion('{% url 'accounts:change_sale' detail.id %}')" class="btn btn-info">Cambiar</button>
            <a href="{% url 'accounts:release' detail.id user.id%}" class="btn btn-danger">Liberar</a>

        </div>

        {% endfor %}

    </div>
    </div>
</section>


<section class="inactivas">
    <div class="header">
        <h4 class="modal-title">Cuentas Inactivas</h4>
    </div>
    <div class="body">
        {% if not inactive_sales %}
        <div class="not_found">
            <h4>No hay cuentas inactivas</h4>
        </div>
        {% endif %}
        {% for detail in inactive_sales %}
        <div class="detail">
            <div class="account">
                <span>Cuenta:</span>
                <p>{{detail.account_id.account_name_id}}</p>
            </div>
            <div class="username">
                <span>Username:</span>
                <p>{{detail.account_id.email}}
                    {% if detail.account_id.renovable == True %}
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-star-fill gold" viewBox="0 0 16 16">
                        <path
                            d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                    </svg>
                    {% endif %}
                </p>
            </div>
            <div class="password">
                <span>Password:</span>
                <p>{{detail.account_id.password}}</p>
            </div>
            <div class="perfil">
                <span>Perfil:</span>
                <p>{{detail.account_id.profile}}</p>
            </div>
            <div class="pin">
                <span>Pin:</span>
                <p>{{detail.account_id.pin}}</p>
            </div>
            <div class="expiration_customer">
                <span>Vencimiento Cliente:</span>
                <p>{{detail.expiration_date|date:'d-M-Y' }}</p>
            </div>
            <div class="expiration_account">
                <span>Vencimiento Cuenta:</span>
                <p>{{detail.account_id.expiration_date|date:'d-M-Y'}}</p>
            </div>
            <div class="user_seller_id">
                <span>Modificado por:</span>
                <p>{{detail.user_seller_id}}</p>
            </div>
        </div>

        {% endfor %}

    </div>
    </div>
</section>



{% endif %}
{% endblock body %}

{% block extrajs %}
<script>
    $(document).ready(function () {
        $('.toast').toast('show');
    });
</script>
<script>
    function copyToClipBoard() {

        var content = document.getElementById('textArea');
        
        content.select();
        document.execCommand('copy');
    
        alert("Copiado!");
    }
</script>
{% endblock extrajs %}

accounts/templates/accounts/update_sale.html
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Editar Vencimiento de {{sale.account_id}} Perfil {{sale.account_id.profile}} </h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{% url 'accounts:update_sale' sale.id %}" method="POST">
            {% csrf_token %}
            <div class="modal-body mb-3">

                <div class="mb-3">
                    <label for="expiration_date" class="col-form-label">{{form.expiration_date.label}}:</label>
                    {{form.expiration_date}}
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <input type="submit" class="btn btn-primary" value="Editar">
            </div>
        </form>
    </div>
</div>