accounts/urls.py
#django
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "accounts"
urlpatterns = [
    #extension: /accounts/
    path("", views.LoginFormView.as_view(redirect_authenticated_user=True), name ="index"),
    path("dashboard/", login_required(views.DashboardView.as_view()), name ="dashboard"),
    path("logout/", views.LogoutFormView.as_view(), name="logout"),
    path("list_account/", login_required(views.ActiveAccountFunc),name="list_account"),
    path("list_account/create/", login_required(views.CreateAccounts), name="create_account"),
    path("list_account/edit/<int:pk>/", login_required(views.EditAccountView.as_view()), name="edit"),
    path("list_account/edit/layoff_layon/<str:account_name_id>/<str:email>/<int:status>", login_required(views.LayoffLayonAccountFunc), name="layoff_layon"),
    path("list_account/detail/<int:pk>/", login_required(views.DetailAccountFunc), name="detail"),
    path("sales/", login_required(views.SaleFunc),name="sales"),
    path("sales/redeem/find", login_required(views.FindCuponFunc),name="find_cupon"),
    path("sales/redeem/<int:pk>", login_required(views.RedeemFunc),name="redeem"),
    path("sales/renew/<int:pk>/", login_required(views.RenewSale), name="renew_sale"),
    path("sales/update/<int:pk>/", login_required(views.UpdateSale), name="update_sale"),
    path("sales/update/change_sale/<int:pk>/", login_required(views.ChangeSaleFunc), name="change_sale"),
    path("sales/create/<int:pk>", login_required(views.NewSaleFunc), name='create'),
    path("customer/create/", login_required(views.NewCustomerFunc), name='new_customer'),
    path("release/<int:pk>/<int:user>/", login_required(views.ReleaseAccountFunc), name='release')
    ]

cuentas_mexico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'))
]

accounts/views.py
#python
import datetime
from uuid import UUID
from dateutil.relativedelta import relativedelta


#django
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import permission_required
from django.contrib import messages
from django.utils import timezone


#local
from .models import Account,AccountName,UserDetail,Status,Sale,Customer,PaymentMethod, Bank, Cupon
from .forms import CreateAccountForm, FilterAccountForm, EditAccountForm, SaleForm, UpdateSaleForm, ChangeSaleForm, NewCustomerForm, RedeemForm, FindCuponForm
from .functions import SearchExistent, UpdateAccount


## Login - Logour
class LoginFormView(LoginView):
    """
    Show Login page
    """
    template_name= 'accounts/index.html'
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Iniciar Sesión'
        return context

class LogoutFormView(LogoutView):
    """
    Logout user
    """
    pass

# Admin Views
class DashboardView(generic.TemplateView):
    """
    Show all data of template
    """
    model = User
    template_name = 'accounts/dashboard.html'
    today_sales=514
    year_sales=today_sales*365
    comparation = 3.5
    goal = 75

    def get_color(goal):
        if goal <= 30:
            return 'danger'
        elif goal >=31 and goal <= 70:
            return 'warning'
        else:
            return 'success'

    def get_best_sellers(day=None,year=None):
        best_seller = {
            'Netflix':{
            'value':500,
            'percentage':25
            },
            'Spotify':{
            'value':2000,
            'percentage': 75
            }
        }
        return best_seller

    def chart_data(object_data):
        """
        Get an object (dict), and return a list with labels
        """
        labels=[]
        datas=[]
        for label,data in object_data.items():
            labels.append(label)
            datas.append(list(data.values())[0])
        return labels,datas

    def get_context_data(self, **kwargs):
        goal = self.goal
        context = super().get_context_data(**kwargs)
        context['today_sale'] = self.today_sales
        context['year_sale'] = self.year_sales
        context['comparation'] = self.comparation
        context['goal'] = goal
        context['color'] = DashboardView.get_color(goal)
        context['best_sellers_day'] = DashboardView.get_best_sellers(day=timezone.now())
        context['best_sellers_day_label'] = DashboardView.chart_data(context['best_sellers_day'])[0]
        context['best_sellers_day_data'] = DashboardView.chart_data(context['best_sellers_day'])[1]
        context['best_sellers_year'] = DashboardView.get_best_sellers(year=datetime.datetime.today().strftime('%Y'))
        return context

@permission_required('accounts.view_account', raise_exception=True)
def ActiveAccountFunc(request):
    """
    Show all active accounts filtered by Bussiness ID of person are looking for And Pagintate by 10
    """
    business_id = SearchExistent.get_business_id(request)
    available_accounts = SearchExistent.get_available_accounts(request)
    form = FilterAccountForm()
    if request.method == 'POST':
        account_name_id=request.POST['account_name_id']
        email = request.POST['email']
        status_id = request.POST['status_id']
        if email == '---------':
            accounts = Account.objects.filter(
            business_id= business_id,
            account_name_id=account_name_id,
            status_id=status_id
            )
        else:
            accounts = Account.objects.filter(
                business_id= business_id,
                account_name_id=account_name_id,
                email=email,
                status_id=status_id
                )
            #Set Up Pagination
        p =Paginator(accounts, 9)
        page = request.GET.get('page')
        venues = p.get_page(page)
        return render(request, "accounts/active_accounts.html",{
            "accounts": accounts,
            "venues": venues,
            "form": form,
            'available_accounts':available_accounts
        })
    else:
        active = 1
        accounts = Account.objects.filter(status_id=active, business_id= business_id)
            #Set Up Pagination
        p =Paginator(accounts, 9)
        page = request.GET.get('page')
        venues = p.get_page(page)
        return render(request, "accounts/active_accounts.html",{
            "accounts": accounts,
            "venues": venues,
            "form": form,
            'available_accounts':available_accounts
        })

def CreateAccounts(request):
    """
    Add new account to actual bussines are loged in
    """
    if request.method == 'POST':
        form = CreateAccountForm(request.POST)
        user_details = UserDetail
        account = request.POST['account_name_id']
        perfil = AccountName.objects.get(pk=account)
        perfil = perfil.perfil_quantity
        
        if form.is_valid():
            for new_profile in range(1,perfil+1):
                account_name_id = form.cleaned_data['account_name_id']
                supplier = form.cleaned_data['supplier']
                expiration_date = form.cleaned_data['expiration_date']
                email = form.cleaned_data['email']
                password = form.cleaned_data['password']
                pin = form.cleaned_data['pin']
                comments = form.cleaned_data['comments']
                business = form.cleaned_data['business']
                created_by = form.cleaned_data['created_by']
                modified_by = form.cleaned_data['modified_by']
                exist = SearchExistent.search_by_email_account_id(
                    models=Account,
                    account_id=account_name_id,
                    email=email,
                    profile=new_profile
                    )
                if exist == False:
                    Account.objects.create(
                        account_name_id=account_name_id,
                        supplier=supplier,
                        expiration_date=expiration_date,
                        email=email,
                        password=password,
                        pin=pin,
                        comments=comments,
                        business=business,
                        created_by=created_by,
                        modified_by=modified_by,
                        profile=new_profile
                        )
                else:
                    return render(request, 'accounts/create_account.html',{
                        'form': form,
                        'error_message': f"El {account_name_id} con E-Mail {email} ya fue utilizado. Porfavor intenta con uno nuevo."
                    })
        else:
            raise Exception("Formulario No Valido")
        return redirect('accounts:list_account')
    else: 
        form = CreateAccountForm()
    return render(request, 'accounts/create_account.html', {
        'form': form,
    }
        )

class EditAccountView(UpdateView):
    model = Account
    form_class = EditAccountForm
    template_name = 'accounts/update_accounts.html'
    success_url = reverse_lazy('accounts:list_account')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

def DetailAccountFunc(request, pk):
    
    detail = Sale.objects.filter(account_id = pk)

    return render(request,'accounts/detail.html', {
        'detail':detail
    })

def SaleFunc(request,customer=None):
    if request.method=='POST':
        try:
            if customer == None:
                customer = request.POST["customer"]
            else:
                customer = customer

            is_email = False
            is_phone = False
            # now = datetime.now()
            #check if data is email or phone number
            if customer.isnumeric():
                is_phone = True
            else:
                is_email = True
        
                #get customer_id
            if is_email == True:
                customer_id = Customer.objects.get(email__contains=customer)
            if is_phone == True:
                customer_id = Customer.objects.get(phone__contains=customer)
            

            sale_page = SearchExistent.get_customer_sales(request,customer_id=customer_id)
            return render(request,'accounts/sales.html',sale_page)
                
        except(Http404):
            return render(request, "accounts/sales.html",{
                "error_message": "El cliente no existe, verifica que no tenga el codigo de pais"
            })
    return render(request,'accounts/sales.html',{
        'available_accounts':SearchExistent.get_available_accounts(request),
        'new_client': True
    })

def RenewSale(request,pk):
    sale = Sale.objects.get(pk=pk)
    form = SaleForm(request.POST or None, instance=sale)
    available_accounts = SearchExistent.get_available_accounts(request)

    if request.method == 'POST':
        if form.is_valid():
            #find all values
            new_expiration = int(form.data['new_expiration'])
            business = form.cleaned_data['business']
            user_seller_id = form.cleaned_data['user_seller_id']
            bank_id = form.cleaned_data['bank_id']
            customer_id = form.cleaned_data['customer_id']
            account_id = form.cleaned_data['account_id']
            status_id = form.cleaned_data['status_id']
            payment_method_id = form.cleaned_data['payment_method_id']

accounts/templates/template.html
{% load static %}
{% load tags %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/mobile.css'%}"
        media="only screen and (max-width: 760px), (min-device-width: 768px) and (max-device-width: 1024px)">
    <link rel="stylesheet" href="{% static 'accounts/style.css' %}">

    <title>{% block title %}{% endblock title %}</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
</head>

<body>
    {% if user.is_authenticated %}
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'accounts:dashboard' %}">
                    <img src="{% static 'accounts/images/cm_logo.png' %}" alt="Logotipo">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                                href="{% url 'accounts:dashboard' %}">Inicio</a>
                        </li>
                       <!-- <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:sales' %}">Ventas</a>
                        </li>-->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Ventas
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#" onclick="abrir_modal_edicion('{% url 'accounts:new_customer' %}')" >Nuevo Cliente</a></li>
                                <li><a class="dropdown-item" href="#"
                                    onclick="abrir_modal_edicion('{% url 'accounts:find_cupon' %}')">Buscar Cupon</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Cuentas
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'accounts:list_account' %}">Ver Cuentas
                                        Activas</a></li>
                                <li><a class="dropdown-item" href="#"
                                        onclick="abrir_modal_edicion('{% url 'accounts:create_account' %}')">Crear
                                        Cuenta</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Bienvenido {{ user.first_name}}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Perfil</a></li>
                                <li><a class="dropdown-item" href="#">Otros</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Cerrar Sesión</a></li>
                            </ul>
                        </li>

                    </ul>
                    <form action="{% url 'accounts:sales' %}" class="d-flex" role="search" method="POST">
                        {% csrf_token %}
                        <input class="form-control me-2" name="customer" type="text" placeholder="Search"
                            aria-label="Search" required>
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    {% endif %}

    <main>
        {% block body %}

        {% endblock body %}

        {% if error_message %}
        <div aria-live="polite" aria-atomic="true" class="position-relative">
            <div class="toast-container top-0 end-0">
                <div class="toast">
                    <div class="toast-header text-bg-danger">
                        <strong class="me-auto ">ALERTA</strong>
                        <small>ahora</small>
                        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                    </div>
                    <div class="toast-body">
                        {{error_message}}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <div class="modal fade" id="edicion" role="dialog">
        </div>
    </main>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
        integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
        integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous">
    </script>
    <script type="text/javascript">
        var $ = jQuery.noConflict();

        function abrir_modal_edicion(url) {
            $('#edicion').load(url, function () {
                $(this).modal('show');
            });
        }
    </script>

    {% block extrajs %}

    {% endblock extrajs %}

    {% if user.is_authenticated %}
    {% comment %} <footer>
        <p>
            Creado por Eric Martínez, Todos los derechos reservados
        </p>
    </footer> {% endcomment %}

    {% endif %}
</body>

</html>